### ISSUE TITLE
Make options combinable

### ISSUE THREAD

**Issue by bakku** [bakku/peacock#2]
Options are not combinable yet.

e.g. using

`peacock -ev script.rb`

does not work yet.

Either peacock switches to a 3rd-party CI library for ruby or it's own CI class/module will have to be extended

**Comment by Zeragamba** [comment]
you may be able to use the [`optparse`](http://ruby-doc.org/stdlib-2.3.0/libdoc/optparse/rdoc/OptionParser.html) library which is built into ruby.
