### ISSUE TITLE
New option: Cleanup

### ISSUE THREAD

**Issue by bakku** [bakku/peacock#4]
There should be an option for cleaning up a .gitignore file.

The behaviour should be as follows:
- -c/--cleanup should be used
- there should be an optional argument expected with the .gitignore file
- if no .gitignore file was passed then peacock will just search recursively upwards until it finds one
- relatively from the .gitignore file which peacock uses here, it should check if the file or directory in the .gitignore exists, if not then peacock should delete that entry

**Comment by Zeragamba** [comment]
> it should check if the file or directory in the .gitignore exists, if not then peacock should delete that entry

There may be some gitignore entries for files that may be generated, but don't exist yet. Eg. /build.log wouldn't exist until after a build has been completed, and is not something you want in the repo. running --cleanup before a build would remove this line.

I still do like the idea of this feature though as git ignore files can be hard to maintain and clean up as a project grows.

**Comment by bakku** [comment]
@SpyMaster356 
Thank you for your input. I think you have a point.

Maybe the possibility to pass files and directories during the cleanup, e.g.:

```
--cleanup build.log /dist/ other important files
```

which get ignored and not deleted might solve this case sufficiently.

-Bakku
